spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?user=postgres.hxtdbbwfknqncekqdggq&password=jimmyreborn202444&prepareThreshold=0
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # 메타데이터 접근 시의 인증 에러를 방지하는 핵심 옵션입니다.
        temp.use_jdbc_metadata_defaults: false
        format_sql: true